"""empty message

Revision ID: 286f44efa1e1
Revises: 
Create Date: 2021-02-07 17:23:08.188981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '286f44efa1e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'integrations', ['identifier'])
    op.add_column('notification_integration_definitions', sa.Column('extra_parameters', mysql.LONGTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_integration_definitions', 'extra_parameters')
    op.drop_constraint(None, 'integrations', type_='unique')
    # ### end Alembic commands ###
